services:
  app:
    image: serversideup/php:8.3-fpm-nginx
    ports:
      - "8000:8080"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: mami_ga
      DB_USERNAME: mami
      DB_PASSWORD: secret

  mysql:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mami_ga
      MYSQL_USER: mami
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mami_mysql:/var/lib/mysql

volumes:
  mami_mysql:
